### ISSUE TITLE
Breaks Chrome 39.0.2171.52 (2171.52)

### ISSUE THREAD

**Issue by hex** [kemie/Source-Sans-Yosemite-System-Font-Replacement#1]
After switching to Source Sans, I can not open Chrome browser any more.

![Chrome]
(http://i.imgur.com/jQNiOtW.png)

Deleting the fonts solves the problem.

**Comment by lmartins** [comment]
Btw, i've tried https://github.com/seanmpuckett/Myriad-Pro-System-Font-for-Yosemite and it also suffers from the same issue. Still like Source Sans better, it's overall prettier than Myriad to my eyes but would be happy with any of them. Sadly they both kill Chrome on both my machines (2009 Mac Pro and 2014 Macbook Pro).

**Comment by minexew** [comment]
I just wasted 6 hours tracking down this issue.
Should have read the warnings, I guess :/

**Comment by kemie** [comment]
Sorry to hear that @minexew ! I'll try and make it clearer in the readme

**Comment by lmartins** [comment]
It's hard to miss as it is now and a simple search in this repo would have save those 6 hours

**Comment by minexew** [comment]
Meh, @lmartins is probably right.
Of course the best solution would be to fix Chromium. Anybody got a debug build going on?

**Comment by kemie** [comment]
Would someone be willing to test the files from [this pull request](https://github.com/kemie/Source-Sans-Yosemite-System-Font-Replacement/pull/4) to see if it fixes the problem?

**Comment by lmartins** [comment]
I can test it later today

**Comment by deciare** [comment]
The [pull request](https://github.com/kemie/Source-Sans-Yosemite-System-Font-Replacement/pull/4) previously referenced makes Chrome stop crashing on my computer.

It does cause the application name (in bold) to be vertically offset in the menu bar, though. Using the unmodified **System Source Sans Pro Bold.ttf** in conjunction with the other variants from the pull request seems to work best.

**Comment by kemie** [comment]
Good! @lmartins could you check on your system, just so I have double confirmation before I merge? I can look into the bold issue later, i think the crash is more important to fix

**Comment by dtinth** [comment]
I tried the font in the PR, and it works. I think it should be OK to merge.

The latest YosemiteSystemFontPatcher seems to have this bug fixed. dtinth/YosemiteSystemFontPatcher/issues/11

**Comment by kemie** [comment]
I'm going to mark this as fixed, if anyone is still having issues please tell me

**Comment by jasoncostello** [comment]
:sparkles:
